name: deploy
on:
  push:
    tags:
      - '*'
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: open-policy-agent/setup-opa@v1
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm i
      - run: npm run build-policy
      - run: npm test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: open-policy-agent/setup-opa@v1
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm i --production
      - run: npm run build